### ISSUE TITLE
wasmtime v18.0.0 support

### ISSUE THREAD

**Issue by zhen9910** [DouglasDwyer/wasm_component_layer#11]
This crate works great with wasmtime v17 but seems not working with the latest v18.
For example, on V18, wasmtime_environ::Tunables does not have default(), but has default_u32() or default_u64().

https://github.com/DouglasDwyer/wasm_component_layer/blob/30c202620c0b35cdfcaef829ea4e7b70ba4516dc/src/lib.rs#L617

wasmtime-environ-18.0.1
https://docs.rs/wasmtime-environ/latest/wasmtime_environ/struct.Tunables.html#method.default_u32

So, is there a plan to support the latest wasmtime? Thanks

**Comment by DouglasDwyer** [comment]
Yes, I will update the crate to support the latest `wasmtime-environ` shortly. Sorry for the inconvenience - really, the crate should specify `0.17.0` as a dependency to prevent these breaking changes, but I chose to specify support for `>=0.16.0` since WASM-related crates follow such a quick, unpredictable release cycle right now.

**Comment by DouglasDwyer** [comment]
Fixed in version `0.1.16` - please reopen if the issue persists!

**Comment by zhen9910** [comment]
Great, yes, it works and thanks for the prompt update!

**Comment by juntyr** [comment]
First of all, thank you for the amazingly fast update!

> https://github.com/DouglasDwyer/wasm_component_layer/blob/30c202620c0b35cdfcaef829ea4e7b70ba4516dc/src/lib.rs#L617

I think it would be better to use https://docs.rs/wasmtime-environ/latest/wasmtime_environ/struct.Tunables.html#method.default_host since that seems to match the previous default behavior (unless we really don't care about the values and just need *some* default).

**Comment by DouglasDwyer** [comment]
> I think it would be better to use https://docs.rs/wasmtime-environ/latest/wasmtime_environ/struct.Tunables.html#method.default_host since that seems to match the previous default behavior (unless we really don't care about the values and just need some default).

Good suggestion! But I don't think that it matters which `Tunables` is chosen here. `wasmtime-environ` is only used to parse the component types, not compile or generate any code.
